name: SnakemakeWorkflow

on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: snakemake-env
          environment-name: snakemake-env

      - name: Install Snakemake
        run: |
          conda install -y -c bioconda -c conda-forge snakemake-minimal

      - name: Execute Snakemake workflow
        run: |
          snakemake -c1 --configfile .test-workflow/config.yaml --use-conda
